# Generated by Django 5.2.8 on 2025-11-25 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('main', 'Main'), ('child', 'Child')], max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='files.spreadsheetfile')),
            ],
        ),
        migrations.DeleteModel(
            name='ChildFile',
        ),
        migrations.DeleteModel(
            name='MainFile',
        ),
    ]
